---
# plastic_scm defaults

# --- Common ---
plastic_workspace: ""
plastic_api_key: ""
skip_plastic: false

# --- Windows ---
plastic_exe: "C:/Program Files/PlasticSCM5/client/cm.exe"
plastic_cloud_org: ""
plastic_cloud_user: ""

# --- Linux ---
plastic_repo_key_url: "https://www.plasticscm.com/plasticrepo/plasticscm-cloud.gpg.key"
plastic_repo_url: "https://www.plasticscm.com/plasticrepo/plasticscm-cloud-stable/ubuntu"
plastic_repo: ""
plastic_server: "cloud"
plastic_branch: "/main"
