---
# linux_storage defaults

# TODO: Set NFS/SMB mount points when provisioning
# linux_storage_mounts:
#   - src: "192.168.1.61:/zfs-nvme-02/render"
#     dest: "/mnt/render"
#     fstype: nfs
#     opts: "defaults,_netdev"
